# -*- coding: utf-8 -*-
"""Trabalho Prático do Módulo 1.ipynb

Automatically generated by Colab.

# 1. Execute e analise a saída do seguinte código no Google Colab.
"""

inicio = 0
fim = 100

for numero in range(inicio, fim):
  if numero % 5 == 0:
    print(numero)

"""# 2. Altere o código da atividade 1 para que ele exiba os números múltiplos de 2,5 e 7 (simultaneamente) e que estejam dentro do intervalo 100 e 500 (incluindo o 100 e 500)."""

inicio = 100
fim = 501

for numero in range(inicio, fim):
  if numero % 2 == 0 or numero % 5 == 0 or numero % 7 == 0:
    print(numero)

"""# 3. Altere o código da atividade 1, criando uma variável divisor e, em seguida, verifique quais os números no intervalo entre 0 e 1000 (incluindo o 0 e excluindo o 1000) são múltiplos da variável divisor."""

inicio = 0
fim = 1001
divisor = int(input("Digite um número divisor: "))

for numero in range(inicio, fim):
  if numero % divisor == 0:
    print(numero)

"""# 4. Crie um código declarando as seguintes variáveis do tipo string:"""

# variaveis do tipo string
nome = 'João da Silva'
cidade = 'São Paulo'
cpf = '123.456.789-00'

"""Em seguida, realize as seguintes transformações nas variáveis:

- Transforme todos os caracteres em maiusculo;
"""

nome = nome.upper()
cidade = cidade.upper()

print("Nome maiúsculo: ", nome)
print("Cidade maiúsculo: ", cidade)

"""- Transforme todos os caracteres das variáveis em minúsculo;"""

nome = nome.lower()
cidade = cidade.lower()

print("Nome minúsculo: ", nome)
print("Cidade minúsculo: ", cidade)

"""- Exiba a posição do caracter 'ã', se presente, em cada uma das palavras;"""

print("Posição na variável nome: ", nome.find("ã"))
print("Posição na variável cidade: ", cidade.find("ã"))

"""- Exiba o número de caracteres de cada variável"""

print("Número de caracteres da variável nome: ", len(nome))
print("Número de caracteres da variável cidade: ", len(cidade))

"""- Remova os pontos ( . ) e o hífen ( - ) da variável cpf."""

import re

cpf = re.sub(r"[.-]", "", cpf)
print("CPF Tratado: ", cpf)

"""# 5. Crie um código que realize o somátorio de todos os caracteres da seguinte string."""

numero = '127957'

soma = 0
for num in numero:
  soma += int(num)
print("Soma: ", soma)